# http://www.appveyor.com/docs/appveyor-yml

os: Unstable
# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message.
skip_commits:
  message: /updated readme.*/
install:
  - cmd: cinst filezilla.server -y

  - ps: Install-Module -Name Pester -Confirm:$false -Force -ErrorAction SilentlyContinue
  - ps: Install-Module -Name PSScriptAnalyzer -Confirm:$false -Force -ErrorAction SilentlyContinue
build: off
test_script:
  - ps: . .\Tests\appveyor.pester.ps1