#http://www.appveyor.com/docs/appveyor-yml
version: 5.7.7.{build}
os: Unstable
skip_commits:
  message: /updated readme.*/
install:
  - cmd: cinst filezilla.server -y  
  - ps: Copy-Item -Path .\Tests\Requires\* -Destination $env:ProgramFiles\WindowsPowerShell\Modules -Force
build: off
test_script:
  - ps: . .\Tests\appveyor.pester.ps1