os: Unstable
skip_commits:
  message: /updated readme.*/
install:
  - cmd: cinst filezilla.server -y
  
  - ps: Import-Module -Name PowerShellGet -Force
  - ps: PowerShellGet\Install-Module -Name Pester -Confirm:$false -Force
  - ps: PowerShellGet\Install-Module -Name PSScriptAnalyzer -Confirm:$false -Force
build: off
test_script:
  - ps: . .\Tests\appveyor.pester.ps1