# appveyor yml reference
# http://www.appveyor.com/docs/appveyor-yml

version: 5.21.8.{build}
image: Visual Studio 2019
branches:
  only:
    - master
skip_tags: true
only_commits:
  message: /build/
  author: Thomas Malkewitz
skip_commits:
  files:
    README.md
build: off
install:
  - ps: . .\FileZilla\FileZilla_Server_Install.ps1
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$false -Force -ErrorAction Stop | Out-Null
  - ps: Install-Module -Name Configuration, Pester, PSScriptAnalyzer -Confirm:$false -Force -ErrorAction SilentlyContinue | Out-Null
test_script:
  - ps: . .\Invoke-AppveyorBuild.ps1
before_deploy:
  - ps: xcopy .\WinSCP\* .\deploy\ /S | Out-Null
  - ps: Compress-Archive -Path .\deploy\* -DestinationPath .\WinSCP.zip -CompressionLevel Optimal
  - ps: Push-AppveyorArtifact -Path .\WinSCP.zip -FileName WinSCP.zip
# Set Tls to 1.2 so publishing to github actually works.
# https://help.appveyor.com/discussions/questions/18741-publishing-to-github-releases-fails-sending-the-request
  - ps: '[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12'
deploy:
  - provider: GitHub
    release: WinSCP-PowerShell-v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      secure: /uppgpvZIfvBVNh2oEtZB4WYG9Xqx/4+6kO9ykbwDrmRVqe81TLGpXoc5G8oPZdR
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    artifact: WinSCP.zip
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false
environment:
  powershell_gallery_api_token:
    secure: XL6Aqu2HklNdaeNLep/cf1eS9NkTgEC6CXbPHHXEz8auhATxxipNq2sfNrtCPhlH
