# http://www.appveyor.com/docs/appveyor-yml

version: 5.13.0.{build}
os: WMF 5
branches:
  only:
    - master
only_commits:
  message: /build/
  author: dotps1@outlook.com
skip_commits:
  files:
    README.md
install:
  - ps: . .\FileZilla_Server_Install.ps1
  - ps: Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Confirm:$false -Force -ErrorAction Stop | Out-Null
  - ps: Install-Module -Name Configuration, Pester, PSScriptAnalyzer -Confirm:$false -Force -ErrorAction SilentlyContinue | Out-Null
build: off
test_script:
  - ps: . .\Invoke-AppveyorBuild.ps1
before_deploy:
  - ps: xcopy .\WinSCP\* .\deploy\ /S | Out-Null
  - ps: Compress-Archive -Path .\deploy\* -DestinationPath .\WinSCP.zip -CompressionLevel Optimal
  - ps: Push-AppveyorArtifact -Path .\WinSCP.zip -FileName WinSCP.zip
deploy:
  - provider: GitHub
    release: WinSCP-PowerShell-v$(APPVEYOR_BUILD_VERSION)
    auth_token:
      secure: zNRQZ3Yia8BPJrcmjn5x3a0FkrLWCFSgtwaxKGOnBvIiYv6WbWi/ilXezZJclZyE
    description: '$(APPVEYOR_REPO_COMMIT_MESSAGE)'
    artifact: WinSCP.zip
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: false
environment:
  powershell_gallery_api_token:
    secure: feZG1n6/I0hDzxw9VWtlUph94caZUYw3denU0TLudvgWX9cG/jkjDLOT8ixd02P4
#notifications:
#  - provider: Slack
#    incoming_webhook:
#      secure: AbntoBWt4UaZffU0mBhQjuXCQAIegqF1NtTVdnFyinHHS23C+b/r4/lWGDzneboipU5R9/6ti/x1p1ceodafH5iv+il9EyS87/M8TaE3hf8=
