version: 5.7.6.{build}
os: Unstable
install:
- cmd: >-
    cinst filezilla.server -y

    powershell.exe -command "& { Install-Module -Name PSScriptAnalyzer -Force -Confirm:$false; Install-Module -Name Pester -Force -Confirm:$false }
build: off
test_script:
- ps: . .\Tests\appveyor.pester.ps1