name: CI/CD

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch.
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Check repository
        uses: actions/checkout@v3

      # Install Configuration module, used for publishing.
      - name: Install Configuration module
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module -Name Configuration
        
      # Setup and configure FileZilla FTP server to test aginst.
      - name: Install FileZilla FTP server
        shell: pwsh
        run: . .\FileZilla\FileZilla_Server_Install.ps1

      # Import requried modules for testing and publishing.
      - name: Import modules
        shell: pwsh
        run: Import-Module -Name Configuration, Pester, PSScriptAnalyzer

      # Execute Pester tests.
      - name: Execute Pester tests
        shell: pwsh
        run: |
          Import-Module -Name .\WinSCP
          Invoke-Pester -Path .\Tests\* | Export-Clixml -Path .\Pester.Tests.xml

      # Upload Pester test results.
      - name: Upload Pester test results
        uses: actions/upload-artifact@v3
        with:
          name: testResults
          path: .\Pester.Tests.xml

    #if: contains(github.event.head_commit.message, '[Publish]')
