name: CI/CD

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch.
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  build:
    # The type of runner that the job will run on.
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - name: Check repository.
        uses: actions/checkout@v3

      # Update pre installed modules that will be used to test and publish.
      - name: Update pre installed modules.
        shell: pwsh
        run: Update-Module -Name Pester, PSScritpAnalyzer

      # Install Configuration Module, used for publishing.
      - name: Install Configuration Module
        shell: pwsh
        run: Install-Module -Name Configuration -Force
        
      # Setup and configure FileZilla FTP server to test aginst.
      - name: Install FTP Server
        shell: pwsh
        run: . .\FileZilla\FileZilla_Server_Install.ps1

      # Execute Pester Tests.
      - name: Execute Pester Tests
        shell: pwsh
        run: |
          Set-Location -Path $env:GITHUB_WORKSPACE -ErrorAction Stop
          Import-Module -Name Configuration, Pester, PSScriptAanlyzer, ".\WinSCP" -Force -ErrorAction Stop
      
          $pesterConfiguration = [PesterConfiguration]@{
              Run = @{
                  Container = New-PesterContainer -Path ".\Tests"
              }
              Output = @{
                  Verbosity = "Detailed"
              }
              TestResult = @{
                  Enabled = $true
                  OutputPath = "$env:GITHUB_WORKSPACE\testResults.xml"
              }
          }
          Invoke-Pester -Configuration $pesterConfiguration

    #if: contains(github.event.head_commit.message, '[Build]')
